// THIS FILE IS GENERATED - DO NOT EDIT
//
// Copyright
//
// Copyright (c) phloc systems 2004 - 2012
// http://www.phloc.com
//
// All Rights Reserved
// Use, duplication or disclosure restricted by phloc systems
//
// Vienna, 2004 - 2012
// This file was generated by com.phloc.webui.pui.calendar.MainCreateCalendarTranslations2

// full day names, starting and ending with Sunday!
Calendar._DN = new Array
("Sonntag",
 "Montag",
 "Dienstag",
 "Mittwoch",
 "Donnerstag",
 "Freitag",
 "Samstag",
 "Sonntag");

//Please note that the following array of short day names (and the same goes
//for short month names, _SMN) isn't absolutely necessary.  We give it here
//for exemplification on how one can customize the short day names, but if
//they are simply the first N letters of the full name you can simply say:
//
//Calendar._SDN_len = N; // short day name length
//Calendar._SMN_len = N; // short month name length
//
//If N = 3 then this is not needed either since we assume a value of 3 if not
//present, to be compatible with translation files that were written before
//this feature.

// short day names, starting and ending with Sunday
Calendar._SDN = new Array
("So",
 "Mo",
 "Di",
 "Mi",
 "Do",
 "Fr",
 "Sa",
 "So");

// First day of the week. "0" means display Sunday first, "1" means display
// Monday first, etc.
Calendar._FD = 1;

// full month names, from January to December
Calendar._MN = new Array
("Januar",
 "Februar",
 "März",
 "April",
 "Mai",
 "Juni",
 "Juli",
 "August",
 "September",
 "Oktober",
 "November",
 "Dezember");

// short month names, from January to December
Calendar._SMN = new Array
("Jan",
 "Feb",
 "Mär",
 "Apr",
 "Mai",
 "Jun",
 "Jul",
 "Aug",
 "Sep",
 "Okt",
 "Nov",
 "Dez");

// tooltips
Calendar._TT = {};
Calendar._TT["INFO"] = "Über dieses Kalendarmodul";

Calendar._TT["ABOUT"] =
"DHTML Date/Time Selector\n" +
"(c) dynarch.com 2002-2005 / Author: Mihai Bazon\n" + // don't translate this ;-)
"For latest version visit: http://www.dynarch.com/projects/calendar/\n" +
"Distributed under GNU LGPL.  See http://gnu.org/licenses/lgpl.html for details." +
"\n\n" + "Datum auswählen:\n- Benutzen Sie die «, » Buttons um das Jahr zu wählen\n- Benutzen Sie die ‹, › Buttons um den Monat zu wählen\n- Für eine Schnellauswahl halten Sie die Maustaste über diesen Buttons fest.";
Calendar._TT["ABOUT_TIME"] = "\n\n" + "Zeit auswählen:\n- Klicken Sie auf die Teile der Uhrzeit, um diese zu erhöhen\n- oder klicken Sie mit festgehaltener Shift-Taste um diese zu verringern\n- oder klicken und festhalten für Schnellauswahl.";

Calendar._TT["PREV_YEAR"] = "Voriges Jahr (Festhalten für Liste)";
Calendar._TT["PREV_MONTH"] = "Voriger Monat (Festhalten für Liste)";
Calendar._TT["GO_TODAY"] = "Heute auswählen";
Calendar._TT["NEXT_MONTH"] = "Nächst. Monat (Festhalten für Liste)";
Calendar._TT["NEXT_YEAR"] = "Nächst. Jahr (Festhalten für Liste)";
Calendar._TT["SEL_DATE"] = "Datum auswählen";
Calendar._TT["DRAG_TO_MOVE"] = "Zum Bewegen festhalten";
Calendar._TT["PART_TODAY"] = " (Heute)";

// the following is to inform that "%s" is to be the first day of week
// %s will be replaced with the day name.
Calendar._TT["DAY_FIRST"] = "Woche beginnt mit %s";

// This may be locale-dependent.  It specifies the week-end days, as an array
// of comma-separated numbers.  The numbers are from 0 to 6: 0 means Sunday, 1
// means Monday, etc.
Calendar._TT["WEEKEND"] = "0,6";

Calendar._TT["CLOSE"] = "Schließen";
Calendar._TT["TODAY"] = "Heute";
Calendar._TT["TIME_PART"] = "(Shift-)Klick oder Festhalten und Ziehen um den Wert zu ändern";

// date formats
Calendar._TT["DEF_DATE_FORMAT"] = "%d.%m.%Y";
Calendar._TT["TT_DATE_FORMAT"] = "%A, %e. %B";

// phloc added
Calendar._TT["DEF_TIME_FORMAT"] = "%H:%M:%S";

Calendar._TT["WK"] = "KW";
Calendar._TT["TIME"] = "Zeit:";
