/**
 * Copyright (C) 2006-2013 phloc systems
 * http://www.phloc.com
 * office[at]phloc[dot]com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.phloc.tinymce4;

import javax.annotation.Nonnull;

import com.phloc.commons.annotations.Nonempty;
import com.phloc.commons.id.IHasID;

/**
 * All TinyMCE4 supported languages. Note: not all locales here are valid Java
 * locales!<br>
 * Partly generated by MainCreateTinyMCELanguageEnum
 * 
 * @author Philip Helger
 */
public enum ETinyMCE4Language implements IHasID <String>
{
  AR ("ar"),
  BG_BG ("bg_BG"),
  BS ("bs"),
  CA ("ca"),
  CS ("cs"),
  CY ("cy"),
  DA ("da"),
  DE ("de"),
  DE_AT ("de_AT"),
  EL ("el"),
  ES ("es"),
  ET ("et"),
  EU ("eu"),
  FA ("fa"),
  FI ("fi"),
  FO ("fo"),
  FR_FR ("fr_FR"),
  GL ("gl"),
  /* Note: this is not a valid Java locale! */
  HE_IL ("he_IL"),
  HR ("hr"),
  HU_HU ("hu_HU"),
  HY ("hy"),
  /* Note: this is not a valid Java locale! */
  ID ("id"),
  IT ("it"),
  JA ("ja"),
  /* Note: this is not a valid Java locale! */
  KA_GE ("ka_GE"),
  KO_KR ("ko_KR"),
  LB ("lb"),
  LT ("lt"),
  LV ("lv"),
  /* Note: this is not a valid Java locale! */
  NB_NO ("nb_NO"),
  NL ("nl"),
  PL ("pl"),
  PT_BR ("pt_BR"),
  PT_PT ("pt_PT"),
  RO ("ro"),
  RU ("ru"),
  /* Note: this is not a valid Java locale! */
  SI_LK ("si_LK"),
  SK ("sk"),
  SL_SI ("sl_SI"),
  SR ("sr"),
  SV_SE ("sv_SE"),
  TA ("ta"),
  /* Note: this is not a valid Java locale! */
  TA_IN ("ta_IN"),
  TG ("tg"),
  TH_TH ("th_TH"),
  TR_TR ("tr_TR"),
  UG ("ug"),
  UK ("uk"),
  UK_UA ("uk_UA"),
  VI ("vi"),
  VI_VN ("vi_VN"),
  ZH_CN ("zh_CN"),
  ZH_TW ("zh_TW");

  private final String m_sID;

  private ETinyMCE4Language (@Nonnull @Nonempty final String sID)
  {
    m_sID = sID;
  }

  @Nonnull
  @Nonempty
  public String getID ()
  {
    return m_sID;
  }
}
