package com.phloc.tinymce4;

import javax.annotation.Nonnull;

import com.phloc.commons.annotations.Nonempty;
import com.phloc.commons.id.IHasID;

/**
 * All TinyMCE4 supported plugins.<br>
 * Partly generated by MainCreateTinyMCEPluginEnum
 * 
 * @author Philip Helger
 */
public enum ETinyMCE4Plugin implements IHasID <String>
{
  ADVLIST ("advlist"),
  ANCHOR ("anchor"),
  AUTOLINK ("autolink"),
  AUTORESIZE ("autoresize"),
  AUTOSAVE ("autosave"),
  BBCODE ("bbcode"),
  CHARMAP ("charmap"),
  CODE ("code"),
  COMPAT3X ("compat3x"),
  CONTEXTMENU ("contextmenu"),
  DIRECTIONALITY ("directionality"),
  EMOTICONS ("emoticons"),
  EXAMPLE ("example"),
  EXAMPLE_DEPENDENCY ("example_dependency"),
  FULLPAGE ("fullpage"),
  FULLSCREEN ("fullscreen"),
  HR ("hr"),
  IMAGE ("image"),
  IMPORTCSS ("importcss"),
  INSERTDATETIME ("insertdatetime"),
  LAYER ("layer"),
  LEGACYOUTPUT ("legacyoutput"),
  LINK ("link"),
  LISTS ("lists"),
  MEDIA ("media"),
  NONBREAKING ("nonbreaking"),
  NONEDITABLE ("noneditable"),
  PAGEBREAK ("pagebreak"),
  PASTE ("paste"),
  PREVIEW ("preview"),
  PRINT ("print"),
  SAVE ("save"),
  SEARCHREPLACE ("searchreplace"),
  SPELLCHECKER ("spellchecker"),
  TABFOCUS ("tabfocus"),
  TABLE ("table"),
  TEMPLATE ("template"),
  TEXTCOLOR ("textcolor"),
  VISUALBLOCKS ("visualblocks"),
  VISUALCHARS ("visualchars"),
  WORDCOUNT ("wordcount");

  private final String m_sID;

  private ETinyMCE4Plugin (@Nonnull @Nonempty final String sID)
  {
    m_sID = sID;
  }

  @Nonnull
  @Nonempty
  public String getID ()
  {
    return m_sID;
  }
}
