package com.phloc.tinymce4;

import javax.annotation.Nonnull;

import com.phloc.commons.annotations.Nonempty;
import com.phloc.commons.id.IHasID;

/**
 * All TinyMCE4 supported themes.<br>
 * Partly generated by MainCreateTinyMCEThemeEnum
 * 
 * @author Philip Helger
 */
public enum ETinyMCE4Theme implements IHasID <String>
{
  MODERN ("modern");

  private final String m_sID;

  private ETinyMCE4Theme (@Nonnull @Nonempty final String sID)
  {
    m_sID = sID;
  }

  @Nonnull
  @Nonempty
  public String getID ()
  {
    return m_sID;
  }
}
