package com.phloc.tinymce4;

import javax.annotation.Nonnull;

import com.phloc.commons.annotations.Nonempty;
import com.phloc.commons.id.IHasID;

/**
 * All TinyMCE4 supported skins.<br>
 * Partly generated by MainCreateTinyMCESkinEnum
 * 
 * @author Philip Helger
 */
public enum ETinyMCE4Skin implements IHasID <String>
{
  LIGHTGRAY ("lightgray");

  private final String m_sID;

  private ETinyMCE4Skin (@Nonnull @Nonempty final String sID)
  {
    m_sID = sID;
  }

  @Nonnull
  @Nonempty
  public String getID ()
  {
    return m_sID;
  }
}
